### PR TITLE
Feat/auditor employee files

### LINKED ISSUE #125: Switchable Employee files field (grid / list view)
Create 2 types of view in employee files

### PR DESCRIPTION
**Pull request by glendell03**
# Description

- Auditor Employee file page initial
- Switchable view 
May bug lang sa grid view hahah pa help guys 

Fixes #125 #57 

# Type of change

Please delete options that are not relevant.

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] This change requires a documentation update

# Screenshots (if appropriate)

image

# Checklist:

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [ ] My changes generate no new warnings
-   [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by glendell03** [comment]
@CloudyMushroom  pa help sa css hahah

**Comment by franzegos** [comment]
Nice nice pwede na to merge after ma solve nung sa grid view

**Comment by glendell03** [comment]
> Nice nice pwede na to merge after ma solve nung sa grid view

wag din muna imerge hahaha madami pa kulang 
di ko lang maayos yung sa grid hahaha pa help guys

**Comment by CloudyMushroom** [comment]
Wait now ko lang nakita salamt kay Franz
Tignan ko.

**Comment by glendell03** [comment]
yoon salamaaats

**Comment by CloudyMushroom** [comment]
Bago ko magawa 'to dapat yung last 3 branches ko ma-merge para yung components non magamit ko sana
image
image
image

**Comment by CloudyMushroom** [comment]
yung attempt 2, siguro stop muna ako jan, Since na fix ko kasi yung sidebar; subukan ko balik yung ginawa ni @glendell03 para konting modifications na lang. I will name it Attempt 2.1 kung sakaling makayanan kapag hindi proceed na lang ako sa sarili kong recreation ng aud/ emp file page.

**Comment by franzegos** [comment]
@glendell03 merge ko na to pri fixed na yung grid, yung mga kulang gawan nalang ng branch like yung content ng list/grid. Para pag open ng auditor.employee file goods na

**Pull request merged**
