### PR TITLE
fix: employee file crashing

### PR DESCRIPTION
**Pull request by glendell03**
# Description

- Fix employee file route crash

# Type of change

Please delete options that are not relevant.

-   [x] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] This change requires a documentation update

# Screenshots (if appropriate)

image

# Checklist:

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [ ] My changes generate no new warnings
-   [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by franzegos** [comment]
Gumagana na yung employee file prii problema di parin makapag login tsaka wlaang laman yung mga tables sa UI, sa database meron hahaha
image

**Comment by glendell03** [comment]
gumagana sakin yung login ano error lumalabas sayo?

**Comment by franzegos** [comment]
> gumagana sakin yung login ano error lumalabas sayo?

Wala loading lang pre pag nag llogin, wait try ko delete yung database ko tas gawa ulit bagoo

**Comment by franzegos** [comment]
Okay na HAHAHA, proceed kana @CloudyMushroom

**Pull request merged**
