### PR TITLE
DONE PAYROLL FRAME Aud/payroll frame

### PR DESCRIPTION
**Pull request by CloudyMushroom**
All goods na payroll frame

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

# Type of change

Please delete options that are not relevant.

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] This change requires a documentation update

# Screenshots (if appropriate)

Add screenshots that could help the reviewer.

# Checklist:

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [ ] My changes generate no new warnings
-   [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by franzegos** [comment]
After nalang nung "view" dun sa auditor.payroll table to ilipat no? Kaso pano yun sir next na is yung windows ng for approval?

**Comment by CloudyMushroom** [comment]
Sa Attendance nakalagay yun boss Hindi sa For-Approval na page

**Comment by CloudyMushroom** [comment]
@glendell03 pa help kami malipat sa aud/payroll -> view yung ginawa ko sa attendance page. Hirap pa kasi ako maglagay ng ganon pre for CSS palang kasi talaga ako hahaha

**Comment by CloudyMushroom** [comment]
image
Click view then picture below will show
image

**Comment by franzegos** [comment]
Oks naaaa, iddelete na yung payroll window sa attendance tab bago merge to sirrr?

**Comment by glendell03** [comment]
> Oks naaaa, iddelete na yung payroll window sa attendance tab bago merge to sirrr?

uu oks na to delete nalang yung sa attendance

**Pull request merged**
