### PR TITLE
Feat/logout

### LINKED ISSUE #100: Stay at the same page after refresh
Dapat kung nasa route /employee-file ka tapos nagrefresh ka, dapat nasa /employee-file ka pa din.

### PR DESCRIPTION
**Pull request by glendell03**
# Description

- fix log out bug
- redesign sidebar base on role
- nilagay ko yung role sa localstorage kasi kapag nag rerefresh nawawala yung state hindi ko alam kung bakit hahah

Fixes #100 

# Type of change

Please delete options that are not relevant.

-   [x] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] This change requires a documentation update

# Screenshots (if appropriate)

Add screenshots that could help the reviewer.

# Checklist:

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [ ] My changes generate no new warnings
-   [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by glendell03** [comment]
@franzegos @yell66w pa review ulit kung okay na siya

**Comment by yell66w** [comment]
@glendell03 mawawala talaga yung state kada refresh yung walang redux-persist haha

**Comment by glendell03** [comment]
ahhh so need natin talaga non? hahaha

**Comment by yell66w** [comment]
Bugged pa pre. 
1. Login
2. Refresh page
3. Click sa ibang route
4. Error: Maximum update depth exceeded. 
Screenshot_20211103_182207

**Comment by yell66w** [comment]
Pwede din naman natin to iskip lang muna, di pa naman gaano ka priority pag logout haha

**Comment by glendell03** [comment]
oshiiii HAHAHA kala ko wala na yan arggh

**Pull request merged**
